./moksha-ctl.py script is in good shape.
To get help:
  $ ./moksha-ctl.py --help

To quickstart:
  $ ./moksha-ctl.py --environment=yourmother bootstrap rebuild start wtf

diff --git a/.scripts/start-orbited b/.scripts/start-orbited
--- a/.scripts/start-orbited
+++ b/.scripts/start-orbited
@@ -1,4 +1,17 @@
-#!/bin/bash -x
-echo "-------------- Trying to start up --------------" >> logs/orbited.log
-nohup orbited -c orbited.cfg >> logs/orbited.log 2>&1 < /dev/null &
-echo $! >> orbited.pid
+#!/bin/bash -e
+source ~/.bashrc
+export LOG=logs/orbited.log
+
+echo "-------------- Trying to start up --------------" >> $LOG
+if test -z "$1"
+then
+        echo "No virtualenv argument supplied.  Aborting." >> $LOG
+        exit 1
+else
+        echo "Using virtualenv $1" >> $LOG
+fi
+source $WORKON_HOME/$1/bin/activate
+orbited -c orbited.cfg >> logs/orbited.log 2>&1 < /dev/null &
+echo $! > orbited.pid
+
+exit 0
diff --git a/.scripts/start-paster b/.scripts/start-paster
--- a/.scripts/start-paster
+++ b/.scripts/start-paster
@@ -1,4 +1,16 @@
-#!/bin/bash -x
-echo "-------------- Trying to start up --------------" >> logs/paster.log
-nohup paster serve development.ini >> logs/paster.log 2>&1 < /dev/null &
-echo $! >> paster.pid
+#!/bin/bash -e
+source ~/.bashrc
+export LOG=logs/paster.log
+
+echo "-------------- Trying to start up --------------" >> $LOG
+if test -z "$1"
+then
+        echo "No virtualenv argument supplied.  Aborting." >> $LOG
+        exit 1
+else
+        echo "Using virtualenv $1" >> $LOG
+fi
+source $WORKON_HOME/$1/bin/activate
+paster serve development.ini >> logs/paster.log 2>&1 < /dev/null &
+echo $! > paster.pid
+exit 0
